// Perguntas de Administração — SHOW DO MILHÃO SAEP ADM 023
// Cada item: { q, options: [A,B,C,D], answer: 0..3 }
const QUESTION_BANK = [
  { q: "Qual é a função principal do planejamento na administração?", options: ["Organizar tarefas", "Definir metas e caminhos", "Controlar recursos", "Executar ações"], answer: 1 },
  { q: "A análise SWOT avalia:", options: ["Cultura e clima", "Forças, Fraquezas, Oportunidades e Ameaças", "Apenas finanças", "Apenas operações"], answer: 1 },
  { q: "Em organogramas, a linha pontilhada geralmente indica:", options: ["Chefia direta", "Relação matricial/assessoria", "Demissão", "Promoção"], answer: 1 },
  { q: "O ciclo PDCA significa:", options: ["Plan, Do, Check, Act", "Prepare, Do, Control, Audit", "Plan, Direct, Control, Act", "Process, Develop, Control, Act"], answer: 0 },
  { q: "Fluxo de caixa é:", options: ["Lucro contábil", "Entradas e saídas de dinheiro", "Investimentos futuros", "Apenas despesas fixas"], answer: 1 },
  { q: "ROI mede:", options: ["Retorno sobre investimento", "Risco operacional", "Rotatividade interna", "Receita operacional líquida"], answer: 0 },
  { q: "O objetivo do controle interno é:", options: ["Eliminar auditorias", "Reduzir riscos e fraudes", "Aumentar burocracia", "Crescer receita"], answer: 1 },
  { q: "5S NÃO inclui:", options: ["Seiri", "Seiton", "Seisou", "Seikaku"], answer: 3 },
  { q: "Indicadores SMART devem ser:", options: ["Simples e lentos", "Específicos, Mensuráveis, Atingíveis, Relevantes e Temporais", "Amplos e qualitativos", "Somente financeiros"], answer: 1 },
  { q: "Custo fixo é aquele que:", options: ["Varia com produção", "Não varia no curto prazo", "É imposto", "É comissão"], answer: 1 },
  { q: "Break-even (ponto de equilíbrio) ocorre quando:", options: ["Receita = Custos totais", "Lucro máximo", "Perda mínima", "Custos variáveis = 0"], answer: 0 },
  { q: "Mix de marketing (4Ps) inclui:", options: ["Produto, Preço, Praça, Promoção", "Plano, Preço, Pessoas, Processo", "Produto, Pessoas, Prazo, Promoção", "Preço, Pessoas, Processo, Prova"], answer: 0 },
  { q: "Gestão da qualidade total (TQM) foca em:", options: ["Inspetores", "Melhoria contínua e cliente", "Corte de custos apenas", "Automação"], answer: 1 },
  { q: "Liderança situacional defende que:", options: ["Um estilo único é ideal", "O estilo depende da maturidade da equipe", "Autoritarismo é melhor", "Democracia sempre"], answer: 1 },
  { q: "Kanban é uma técnica de:", options: ["Finanças", "Logística de distribuição", "Controle de fluxo e produção", "RH"], answer: 2 },
  { q: "Job rotation é:", options: ["Demissão voluntária", "Rotatividade de cargos para desenvolvimento", "Terceirização", "Banco de horas"], answer: 1 },
  { q: "Clima organizacional mede:", options: ["Estratégia", "Percepções dos colaboradores", "Apenas salário", "Inventário"], answer: 1 },
  { q: "BPM (Business Process Management) trata de:", options: ["Produtos", "Gestão de processos de negócios", "TI somente", "Vendas"], answer: 1 },
  { q: "Compliance significa:", options: ["Marketing digital", "Conformidade com leis e normas", "Redução de custos", "Promoção de marca"], answer: 1 },
  { q: "Mapa de processos mostra:", options: ["Organograma", "Fluxo das atividades e conexões", "Clientes", "Fornecedores"], answer: 1 },
  { q: "Curva ABC classifica itens por:", options: ["Peso", "Valor/criticidade", "Tamanho", "Volume físico"], answer: 1 },
  { q: "Lead time é:", options: ["Tempo total do processo", "Tempo de setup", "Tempo de ciclo de máquina", "Horas extras"], answer: 0 },
  { q: "ERP é um:", options: ["Sistema integrado de gestão", "Relatório financeiro", "Método de RH", "Norma ISO"], answer: 0 },
  { q: "Kaizen é associado a:", options: ["Grandes revoluções", "Melhoria contínua", "Marketing", "Venda agressiva"], answer: 1 },
  { q: "Turnover elevado indica:", options: ["Retenção alta", "Baixa rotatividade", "Alta rotatividade de pessoal", "Promoções frequentes"], answer: 2 },
  { q: "Ticket médio é:", options: ["Preço de custo", "Preço médio por venda", "Lucro líquido", "Despesa unitária"], answer: 1 },
  { q: "DRE demonstra:", options: ["Lucros e perdas no período", "Fluxo de caixa futuro", "Balanço patrimonial", "Notas explicativas"], answer: 0 },
  { q: "Balanço Patrimonial mostra:", options: ["Receitas e despesas", "Ativos, Passivos e Patrimônio Líquido", "Fluxo operacional", "Caixa do mês"], answer: 1 },
  { q: "Método FIFO em estoque significa:", options: ["Último que entra, primeiro que sai", "Primeiro que entra, primeiro que sai", "Preço médio", "Custo padrão"], answer: 1 },
  { q: "Margem de contribuição é:", options: ["Preço - Custo variável", "Preço - Custo fixo", "Custo total - Receita", "Lucro líquido"], answer: 0 },
  { q: "Indicador 'absenteísmo' mede:", options: ["Vendas", "Faltas/ausências de colaboradores", "Produtividade de máquinas", "Lucro"], answer: 1 },
  { q: "Benchmarking é:", options: ["Copiar concorrentes", "Comparar e aprender com melhores práticas", "Auditar fraudes", "Cortar custos"], answer: 1 },
  { q: "Metodologia 5W2H ajuda a:", options: ["Definir quem, o quê, quando, onde, por quê, como e quanto", "Definir orçamento", "Contratar pessoas", "Fazer organograma"], answer: 0 },
  { q: "CAPEX refere-se a:", options: ["Despesas operacionais", "Investimentos em capital", "Impostos diretos", "Custo variável"], answer: 1 },
  { q: "OEE mede:", options: ["Eficiência global de equipamentos", "Satisfação do cliente", "Lucratividade", "Clima organizacional"], answer: 0 },
  { q: "LGPD no Brasil trata de:", options: ["Crédito bancário", "Proteção de dados pessoais", "Segurança patrimonial", "Contabilidade"], answer: 1 },
  { q: "Matriz BCG avalia:", options: ["Produtos/Unidades por participação e crescimento", "Risco financeiro", "Rotatividade", "Clima"], answer: 0 },
  { q: "Custos diretos são:", options: ["Impossíveis de rastrear", "Relacionados diretamente ao produto/serviço", "Apenas administrativos", "Somente impostos"], answer: 1 },
  { q: "Backoffice geralmente inclui:", options: ["Vendas externas", "Áreas de suporte (fin., RH, TI)", "Marketing de campo", "Atendimento presencial"], answer: 1 },
  { q: "Just-in-time busca:", options: ["Estoques elevados", "Produzir apenas no momento da demanda", "Compras anuais", "Mais inspeção"], answer: 1 },
  { q: "Análise de Pareto sugere foco em:", options: ["100% dos problemas", "20% das causas que geram 80% dos efeitos", "Apenas custos", "Clientes novos"], answer: 1 }
];
